/**
 * VSee Clinic — Design System (shadcn/ui edition)
 *
 * Every component below is imported from src/components/ui/*
 * Those files were generated by: npx shadcn@latest add <component>
 *
 * Run: npm install && npm run dev
 */
import { useState } from "react"
import "./App.css"

// ─── shadcn/ui components ────────────────────────────────────────────────────
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import { Switch } from "@/components/ui/switch"
import { Checkbox } from "@/components/ui/checkbox"
import { Alert, AlertTitle, AlertDescription } from "@/components/ui/alert"
import { Progress } from "@/components/ui/progress"
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs"
import { Avatar, AvatarFallback } from "@/components/ui/avatar"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { Separator } from "@/components/ui/separator"

// ─── lucide-react icons ───────────────────────────────────────────────────────
import {
  CheckCircle, Info, AlertTriangle, XCircle,
  Search, Bell, User,
  MessageSquare, FlaskConical,
  ChevronLeft, ChevronRight,
} from "lucide-react"

// ─── Helper components ────────────────────────────────────────────────────────

function SectionLabel({ children }: { children: React.ReactNode }) {
  return (
    <p className="text-xs font-bold uppercase tracking-widest text-primary mb-2">
      {children}
    </p>
  )
}

function SectionTitle({ children }: { children: React.ReactNode }) {
  return (
    <h2 className="text-4xl font-extrabold tracking-tight text-foreground mb-3">
      {children}
    </h2>
  )
}

function SectionDesc({ children }: { children: React.ReactNode }) {
  return (
    <p className="text-base text-muted-foreground max-w-2xl leading-relaxed mb-12">
      {children}
    </p>
  )
}

function SubTitle({ children }: { children: React.ReactNode }) {
  return (
    <h3 className="text-lg font-bold text-foreground mb-4">{children}</h3>
  )
}

function Preview({ children, vertical = false }: { children: React.ReactNode; vertical?: boolean }) {
  return (
    <div className={`bg-muted rounded-lg p-6 flex flex-wrap gap-3 items-center ${vertical ? "flex-col items-stretch" : ""}`}>
      {children}
    </div>
  )
}

function Subsection({ children }: { children: React.ReactNode }) {
  return <div className="mb-12">{children}</div>
}

// ─── Swatch component ─────────────────────────────────────────────────────────

function ColorSwatch({ hex, name, token }: { hex: string; name: string; token: string }) {
  const [copied, setCopied] = useState(false)
  return (
    <button
      className="flex-1 min-w-28 max-w-44 rounded-lg border bg-card overflow-hidden hover:-translate-y-0.5 hover:shadow-md transition-all text-left"
      onClick={() => { navigator.clipboard.writeText(hex); setCopied(true); setTimeout(() => setCopied(false), 1500) }}
      aria-label={`Copy ${hex}`}
    >
      <div className="h-20 relative" style={{ background: hex }}>
        {copied && (
          <div className="absolute inset-0 flex items-center justify-center bg-black/40 text-white text-xs font-semibold">
            Copied!
          </div>
        )}
      </div>
      <div className="p-2.5">
        <div className="text-sm font-semibold">{name}</div>
        <div className="text-xs text-muted-foreground font-mono">{hex}</div>
        <div className="text-[10px] text-muted-foreground font-mono mt-0.5">{token}</div>
      </div>
    </button>
  )
}

// ─── Status badge ─────────────────────────────────────────────────────────────

function StatusBadge({ variant, children }: {
  variant: "ordered" | "scheduled" | "overdue" | "in-progress" | "cancelled" | "resulted" | "completed"
  children: React.ReactNode
}) {
  const styles: Record<string, string> = {
    ordered:     "bg-green-50 text-green-800 border-green-200",
    scheduled:   "bg-blue-50 text-blue-800 border-blue-200",
    overdue:     "bg-red-50 text-red-800 border-red-200",
    "in-progress": "bg-amber-50 text-amber-800 border-amber-200",
    cancelled:   "bg-gray-100 text-gray-600 border-gray-200",
    resulted:    "bg-green-50 text-green-800 border-green-200",
    completed:   "bg-gray-100 text-gray-700 border-gray-200",
  }
  const dotColors: Record<string, string> = {
    ordered: "bg-green-600", scheduled: "bg-blue-600", overdue: "bg-red-600",
    "in-progress": "bg-amber-500", cancelled: "bg-gray-400",
    resulted: "bg-green-600", completed: "bg-gray-600",
  }
  return (
    <span className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-semibold border ${styles[variant]}`}>
      <span className={`w-1.5 h-1.5 rounded-full ${dotColors[variant]}`} aria-hidden="true" />
      {children}
    </span>
  )
}

// ─── Nav link ─────────────────────────────────────────────────────────────────

function NavLink({ href, active, children }: { href: string; active?: boolean; children: React.ReactNode }) {
  return (
    <a
      href={href}
      className={`block px-2 py-1.5 text-sm font-medium rounded-md transition-colors ${
        active
          ? "bg-accent text-accent-foreground font-semibold"
          : "text-muted-foreground hover:text-foreground hover:bg-muted"
      }`}
    >
      {children}
    </a>
  )
}

// ─── Main App ─────────────────────────────────────────────────────────────────

export default function App() {
  const [notifications, setNotifications] = useState(true)
  const [darkMode, setDarkMode] = useState(false)
  const [showConsultations, setShowConsultations] = useState(true)
  const [myPatients, setMyPatients] = useState(false)

  return (
    <div className="flex min-h-screen bg-background font-sans">

      {/* ── Sticky Sidebar Nav ── */}
      <nav
        className="fixed top-0 left-0 w-60 h-screen bg-card border-r border-border py-6 overflow-y-auto z-20"
        aria-label="Design System Navigation"
      >
        <div className="px-5 pb-5 border-b border-border mb-4">
          <div className="text-xl font-extrabold text-primary tracking-tight">VSee</div>
          <div className="text-[11px] text-muted-foreground font-medium mt-0.5">Design System v4 · shadcn/ui</div>
        </div>

        <div className="px-3 mb-4">
          <div className="text-[11px] font-bold uppercase tracking-widest text-muted-foreground px-2 mb-1">Foundations</div>
          <NavLink href="#colors" active>Colors</NavLink>
          <NavLink href="#typography">Typography</NavLink>
          <NavLink href="#spacing">Spacing</NavLink>
        </div>

        <div className="px-3 mb-4">
          <div className="text-[11px] font-bold uppercase tracking-widest text-muted-foreground px-2 mb-1">Components</div>
          <NavLink href="#buttons">Buttons</NavLink>
          <NavLink href="#forms">Form Elements</NavLink>
          <NavLink href="#badges">Badges & Status</NavLink>
          <NavLink href="#feedback">Feedback</NavLink>
          <NavLink href="#navigation">Navigation</NavLink>
          <NavLink href="#data">Data Display</NavLink>
        </div>

        <div className="px-3 mb-4">
          <div className="text-[11px] font-bold uppercase tracking-widest text-muted-foreground px-2 mb-1">Patterns</div>
          <NavLink href="#emr">EMR Patterns</NavLink>
          <NavLink href="#theming">White-Label</NavLink>
        </div>

        <div className="px-3">
          <div className="text-[11px] font-bold uppercase tracking-widest text-muted-foreground px-2 mb-1">Engineering</div>
          <NavLink href="#tokens">Design Tokens</NavLink>
        </div>
      </nav>

      {/* ── Main Content ── */}
      <div className="ml-60 flex-1">

        {/* HERO */}
        <header
          className="relative overflow-hidden px-16 py-24 text-white"
          style={{ background: "linear-gradient(135deg, oklch(0.52 0.14 162) 0%, oklch(0.42 0.12 162) 50%, oklch(0.32 0.1 162) 100%)" }}
        >
          <div className="absolute -top-40 -right-20 w-96 h-96 rounded-full opacity-10 bg-white" />
          <div className="inline-block px-4 py-1.5 bg-white/10 rounded-full text-xs font-semibold tracking-widest uppercase mb-6 border border-white/20 backdrop-blur-sm">
            shadcn/ui Edition — March 2026
          </div>
          <h1 className="text-6xl font-black tracking-tighter leading-none mb-4">
            VSee Clinic<br />Design System
          </h1>
          <p className="text-xl font-light opacity-80 max-w-lg leading-relaxed">
            Real shadcn/ui components. Radix UI primitives. Tailwind v4. Every import is the actual library.
          </p>
          <div className="flex gap-12 mt-10">
            {[["60+", "Design Tokens"], ["25+", "Components"], ["AA", "WCAG / 508"], ["4px", "Base Grid"]].map(([val, label]) => (
              <div key={label}>
                <div className="text-3xl font-extrabold">{val}</div>
                <div className="text-sm opacity-70">{label}</div>
              </div>
            ))}
          </div>
          <div className="flex gap-2 flex-wrap mt-6">
            {["shadcn/ui", "Radix UI", "Tailwind v4", "lucide-react", "Section 508"].map(tag => (
              <span key={tag} className="px-3 py-1 bg-white/10 border border-white/20 rounded-full text-xs font-semibold">
                {tag}
              </span>
            ))}
          </div>
        </header>

        {/* ── COLORS ── */}
        <section className="px-16 py-16 border-b border-border max-w-5xl" id="colors">
          <SectionLabel>Foundation</SectionLabel>
          <SectionTitle>Colors</SectionTitle>
          <SectionDesc>
            shadcn/ui stores all colors as CSS variables in oklch format. The <code className="bg-muted px-1.5 py-0.5 rounded text-xs font-mono">@theme inline</code> block in <code className="bg-muted px-1.5 py-0.5 rounded text-xs font-mono">index.css</code> bridges them to Tailwind utilities like <code className="bg-muted px-1.5 py-0.5 rounded text-xs font-mono">bg-primary</code>.
          </SectionDesc>

          <Subsection>
            <SubTitle>Brand (--primary)</SubTitle>
            <div className="flex gap-3 flex-wrap mb-6">
              <ColorSwatch hex="#F0FAF5" name="Accent 50" token="--accent (tint)" />
              <ColorSwatch hex="#D1F0E2" name="Accent" token="--accent" />
              <ColorSwatch hex="#0D875C" name="Primary" token="--primary" />
              <ColorSwatch hex="#0B7550" name="Primary/90" token="bg-primary/90" />
              <ColorSwatch hex="#096843" name="Primary/80" token="bg-primary/80" />
            </div>
          </Subsection>

          <Subsection>
            <SubTitle>Semantic</SubTitle>
            <div className="flex gap-3 flex-wrap">
              <ColorSwatch hex="#0D875C" name="Success" token="text-green-800" />
              <ColorSwatch hex="#0575AD" name="Info" token="text-blue-800" />
              <ColorSwatch hex="#F59E0B" name="Warning" token="text-amber-600" />
              <ColorSwatch hex="#EF4444" name="Destructive" token="--destructive" />
            </div>
          </Subsection>

          <Subsection>
            <SubTitle>shadcn Core Variables</SubTitle>
            <div className="grid grid-cols-2 gap-6">
              <Card>
                <CardHeader>
                  <CardTitle>Surfaces</CardTitle>
                  <CardDescription>background · card · muted · accent</CardDescription>
                </CardHeader>
                <CardContent className="flex flex-col gap-3">
                  {[
                    ["bg-background", "Background", "oklch(1 0 0)"],
                    ["bg-card", "Card", "oklch(1 0 0)"],
                    ["bg-muted", "Muted", "oklch(0.96 0.005 265)"],
                    ["bg-accent", "Accent", "oklch(0.95 0.04 162)"],
                  ].map(([cls, name, val]) => (
                    <div key={name} className="flex items-center gap-3">
                      <div className={`w-10 h-10 rounded-md border border-border shrink-0 ${cls}`} />
                      <div>
                        <div className="text-sm font-semibold">{name}</div>
                        <div className="text-xs text-muted-foreground font-mono">{val}</div>
                      </div>
                    </div>
                  ))}
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>Text Colors</CardTitle>
                  <CardDescription>foreground · muted-foreground · primary</CardDescription>
                </CardHeader>
                <CardContent className="flex flex-col gap-3">
                  {[
                    ["bg-foreground", "Foreground", "Headings, body"],
                    ["bg-muted-foreground", "Muted Foreground", "Descriptions"],
                    ["bg-primary", "Primary", "Links, brand"],
                    ["bg-destructive", "Destructive", "Errors, danger"],
                  ].map(([cls, name, desc]) => (
                    <div key={name} className="flex items-center gap-3">
                      <div className={`w-10 h-10 rounded-md shrink-0 ${cls}`} />
                      <div>
                        <div className="text-sm font-semibold">{name}</div>
                        <div className="text-xs text-muted-foreground font-mono">{desc}</div>
                      </div>
                    </div>
                  ))}
                </CardContent>
              </Card>
            </div>
          </Subsection>
        </section>

        {/* ── TYPOGRAPHY ── */}
        <section className="px-16 py-16 border-b border-border max-w-5xl" id="typography">
          <SectionLabel>Foundation</SectionLabel>
          <SectionTitle>Typography</SectionTitle>
          <SectionDesc>
            Inter is our system font. shadcn/ui uses Tailwind's type scale — class names like <code className="bg-muted px-1.5 py-0.5 rounded text-xs font-mono">text-4xl font-bold</code> instead of fixed pixel values.
          </SectionDesc>

          <Card className="mb-8">
            <CardContent className="p-0 divide-y divide-border">
              {[
                { label: "Display", meta: "text-6xl / font-black", preview: "Design for health", className: "text-6xl font-black tracking-tighter" },
                { label: "H1", meta: "text-5xl / font-extrabold", preview: "Page title", className: "text-5xl font-extrabold tracking-tight" },
                { label: "H2", meta: "text-4xl / font-bold", preview: "Section heading", className: "text-4xl font-bold tracking-tight" },
                { label: "H3", meta: "text-2xl / font-bold", preview: "Subsection", className: "text-2xl font-bold" },
                { label: "H4", meta: "text-xl / font-semibold", preview: "Card title", className: "text-xl font-semibold" },
                { label: "Body LG", meta: "text-base / font-normal", preview: "Body text for longer-form content and introductory paragraphs.", className: "text-base text-muted-foreground" },
                { label: "Body", meta: "text-sm / font-normal", preview: "Standard body text used throughout the application.", className: "text-sm" },
                { label: "Caption", meta: "text-xs / font-medium", preview: "Helper text, timestamps, and metadata", className: "text-xs font-medium text-muted-foreground" },
              ].map(({ label, meta, preview, className }) => (
                <div key={label} className="flex items-baseline gap-6 px-6 py-4">
                  <div className="min-w-40 shrink-0">
                    <div className="text-[11px] font-semibold uppercase tracking-wider text-muted-foreground">{label}</div>
                    <div className="text-xs font-mono text-muted-foreground">{meta}</div>
                  </div>
                  <div className={`flex-1 ${className}`}>{preview}</div>
                </div>
              ))}
            </CardContent>
          </Card>
        </section>

        {/* ── BUTTONS ── */}
        <section className="px-16 py-16 border-b border-border max-w-5xl" id="buttons">
          <SectionLabel>Components</SectionLabel>
          <SectionTitle>Buttons</SectionTitle>
          <SectionDesc>
            shadcn Button uses <code className="bg-muted px-1.5 py-0.5 rounded text-xs font-mono">variant</code> and <code className="bg-muted px-1.5 py-0.5 rounded text-xs font-mono">size</code> props via CVA (class-variance-authority). The <code className="bg-muted px-1.5 py-0.5 rounded text-xs font-mono">asChild</code> prop renders as any element via Radix Slot.
          </SectionDesc>

          <Subsection>
            <SubTitle>Variants</SubTitle>
            <div className="bg-muted rounded-lg p-4 text-xs font-mono text-muted-foreground mb-3">
              {`import { Button } from "@/components/ui/button"`}
            </div>
            <Preview>
              <Button variant="default">Default</Button>
              <Button variant="destructive">Destructive</Button>
              <Button variant="outline">Outline</Button>
              <Button variant="secondary">Secondary</Button>
              <Button variant="ghost">Ghost</Button>
              <Button variant="link">Link</Button>
            </Preview>
          </Subsection>

          <Subsection>
            <SubTitle>Sizes</SubTitle>
            <Preview>
              <Button size="xl">Extra Large</Button>
              <Button size="lg">Large</Button>
              <Button size="default">Default</Button>
              <Button size="sm">Small</Button>
              <Button size="icon" aria-label="Search"><Search className="h-4 w-4" /></Button>
            </Preview>
          </Subsection>

          <Subsection>
            <SubTitle>With Icons (lucide-react)</SubTitle>
            <Preview>
              <Button><Bell className="h-4 w-4" />Notifications</Button>
              <Button variant="outline"><User className="h-4 w-4" />Profile</Button>
              <Button variant="ghost"><Search className="h-4 w-4" />Search</Button>
              <Button variant="destructive"><XCircle className="h-4 w-4" />Delete</Button>
            </Preview>
          </Subsection>

          <Subsection>
            <SubTitle>States</SubTitle>
            <Preview>
              <Button>Default</Button>
              <Button className="bg-primary/90">Hover</Button>
              <Button className="ring-2 ring-ring ring-offset-2">Focus</Button>
              <Button disabled>Disabled</Button>
            </Preview>
          </Subsection>

          <Subsection>
            <SubTitle>Block Buttons</SubTitle>
            <div className="max-w-sm flex flex-col gap-2">
              <Button size="lg" className="w-full">Sign In</Button>
              <Button variant="outline" className="w-full">Create Account</Button>
            </div>
          </Subsection>
        </section>

        {/* ── FORMS ── */}
        <section className="px-16 py-16 border-b border-border max-w-5xl" id="forms">
          <SectionLabel>Components</SectionLabel>
          <SectionTitle>Form Elements</SectionTitle>
          <SectionDesc>
            shadcn form components use Radix UI primitives for accessibility. <code className="bg-muted px-1.5 py-0.5 rounded text-xs font-mono">Label</code> is Radix Label. <code className="bg-muted px-1.5 py-0.5 rounded text-xs font-mono">Switch</code> and <code className="bg-muted px-1.5 py-0.5 rounded text-xs font-mono">Checkbox</code> provide full keyboard + screen reader support.
          </SectionDesc>

          <div className="grid grid-cols-2 gap-6">
            <Card>
              <CardHeader><CardTitle>Text Inputs</CardTitle></CardHeader>
              <CardContent className="flex flex-col gap-4">
                <div className="flex flex-col gap-1.5">
                  <Label htmlFor="email">Email address</Label>
                  <Input id="email" type="email" placeholder="you@example.com" />
                </div>
                <div className="flex flex-col gap-1.5">
                  <Label htmlFor="fullname">Full name <span className="text-destructive">*</span></Label>
                  <Input id="fullname" defaultValue="Penny Ng" />
                  <p className="text-xs text-muted-foreground">As it appears on your medical license</p>
                </div>
                <div className="flex flex-col gap-1.5">
                  <Label htmlFor="phone">Phone <span className="text-destructive">*</span></Label>
                  <Input id="phone" className="border-destructive focus-visible:ring-destructive" aria-invalid="true" aria-describedby="phone-error" />
                  <p className="text-xs text-destructive" id="phone-error" role="alert">Phone number is required</p>
                </div>
                <div className="flex flex-col gap-1.5">
                  <Label htmlFor="search">Search</Label>
                  <div className="relative">
                    <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" aria-hidden="true" />
                    <Input id="search" className="pl-9" placeholder="Search patients..." />
                  </div>
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader><CardTitle>Textarea & Switches</CardTitle></CardHeader>
              <CardContent className="flex flex-col gap-4">
                <div className="flex flex-col gap-1.5">
                  <Label htmlFor="notes">Notes</Label>
                  <Textarea id="notes" placeholder="Add clinical notes..." rows={4} />
                </div>
                <Separator />
                <div className="flex flex-col gap-4">
                  <div className="flex items-center gap-3">
                    {/* Switch from @radix-ui/react-switch */}
                    <Switch
                      id="notifications"
                      checked={notifications}
                      onCheckedChange={setNotifications}
                    />
                    <Label htmlFor="notifications">Notifications enabled</Label>
                  </div>
                  <div className="flex items-center gap-3">
                    <Switch
                      id="darkmode"
                      checked={darkMode}
                      onCheckedChange={setDarkMode}
                    />
                    <Label htmlFor="darkmode">Dark mode</Label>
                  </div>
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader><CardTitle>Checkboxes</CardTitle></CardHeader>
              <CardContent className="flex flex-col gap-3">
                {/* Checkbox from @radix-ui/react-checkbox */}
                <div className="flex items-center gap-2">
                  <Checkbox
                    id="consultations"
                    checked={showConsultations}
                    onCheckedChange={(v) => setShowConsultations(!!v)}
                  />
                  <Label htmlFor="consultations">Show consultations</Label>
                </div>
                <div className="flex items-center gap-2">
                  <Checkbox
                    id="mypatients"
                    checked={myPatients}
                    onCheckedChange={(v) => setMyPatients(!!v)}
                  />
                  <Label htmlFor="mypatients">Only my patients</Label>
                </div>
                <div className="flex items-center gap-2">
                  <Checkbox id="archived" disabled />
                  <Label htmlFor="archived" className="opacity-50">Archived (disabled)</Label>
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader><CardTitle>Disabled State</CardTitle></CardHeader>
              <CardContent className="flex flex-col gap-4">
                <div className="flex flex-col gap-1.5">
                  <Label htmlFor="readonly">Read-only field</Label>
                  <Input id="readonly" defaultValue="Read-only value" disabled />
                </div>
                <div className="flex flex-col gap-1.5">
                  <Label htmlFor="large-search">Large Input</Label>
                  <Input id="large-search" className="h-12 text-base" placeholder="Search by name, ID, or phone..." />
                </div>
              </CardContent>
            </Card>
          </div>
        </section>

        {/* ── BADGES ── */}
        <section className="px-16 py-16 border-b border-border max-w-5xl" id="badges">
          <SectionLabel>Components</SectionLabel>
          <SectionTitle>Badges & Status</SectionTitle>
          <SectionDesc>
            shadcn Badge uses CVA variants. Extended with clinical tonal variants for the EMR module.
          </SectionDesc>

          <Subsection>
            <SubTitle>shadcn Core Variants</SubTitle>
            <div className="bg-muted rounded-lg p-4 text-xs font-mono text-muted-foreground mb-3">
              {`import { Badge } from "@/components/ui/badge"`}
            </div>
            <Preview>
              <Badge variant="default">Default</Badge>
              <Badge variant="secondary">Secondary</Badge>
              <Badge variant="destructive">Destructive</Badge>
              <Badge variant="outline">Outline</Badge>
            </Preview>
          </Subsection>

          <Subsection>
            <SubTitle>Clinical Tonal Variants</SubTitle>
            <Preview>
              <Badge variant="success">Active</Badge>
              <Badge variant="info">Scheduled</Badge>
              <Badge variant="warning">Pending</Badge>
              <Badge variant="danger">Overdue</Badge>
              <Badge variant="neutral">Draft</Badge>
            </Preview>
          </Subsection>

          <Subsection>
            <SubTitle>EMR Order Status</SubTitle>
            <div className="sub-desc text-sm text-muted-foreground mb-4">Custom StatusBadge pattern with dot indicator.</div>
            <Preview>
              <StatusBadge variant="ordered">Ordered</StatusBadge>
              <StatusBadge variant="scheduled">Scheduled</StatusBadge>
              <StatusBadge variant="overdue">Overdue</StatusBadge>
              <StatusBadge variant="in-progress">In Progress</StatusBadge>
              <StatusBadge variant="cancelled">Cancelled</StatusBadge>
              <StatusBadge variant="resulted">Resulted</StatusBadge>
              <StatusBadge variant="completed">Completed</StatusBadge>
            </Preview>
          </Subsection>
        </section>

        {/* ── FEEDBACK ── */}
        <section className="px-16 py-16 border-b border-border max-w-5xl" id="feedback">
          <SectionLabel>Components</SectionLabel>
          <SectionTitle>Feedback</SectionTitle>
          <SectionDesc>
            shadcn Alert uses CVA variants. Progress wraps Radix Progress with auto <code className="bg-muted px-1.5 py-0.5 rounded text-xs font-mono">role="progressbar"</code> and <code className="bg-muted px-1.5 py-0.5 rounded text-xs font-mono">aria-valuenow</code>.
          </SectionDesc>

          <Subsection>
            <SubTitle>Alerts</SubTitle>
            <div className="bg-muted rounded-lg p-4 text-xs font-mono text-muted-foreground mb-3">
              {`import { Alert, AlertTitle, AlertDescription } from "@/components/ui/alert"`}
            </div>
            <div className="flex flex-col gap-3 max-w-2xl">
              <Alert variant="success">
                <CheckCircle className="h-4 w-4" />
                <AlertTitle>Changes saved</AlertTitle>
                <AlertDescription>Your patient record has been updated successfully.</AlertDescription>
              </Alert>
              <Alert variant="info">
                <Info className="h-4 w-4" />
                <AlertTitle>Appointment reminder</AlertTitle>
                <AlertDescription>Your next appointment is scheduled for tomorrow at 2:00 PM.</AlertDescription>
              </Alert>
              <Alert variant="warning">
                <AlertTriangle className="h-4 w-4" />
                <AlertTitle>Outstanding balance</AlertTitle>
                <AlertDescription>This patient has an unpaid balance of $45.00.</AlertDescription>
              </Alert>
              <Alert variant="destructive">
                <XCircle className="h-4 w-4" />
                <AlertTitle>Form submission failed</AlertTitle>
                <AlertDescription>Please check the required fields and try again.</AlertDescription>
              </Alert>
            </div>
          </Subsection>

          <Subsection>
            <SubTitle>Progress (Radix Progress)</SubTitle>
            <div className="bg-muted rounded-lg p-4 text-xs font-mono text-muted-foreground mb-3">
              {`import { Progress } from "@/components/ui/progress"`}
            </div>
            <Card className="max-w-md">
              <CardContent className="pt-6 flex flex-col gap-5">
                {[
                  { label: "Profile Complete", value: 75 },
                  { label: "Upload Progress", value: 45, className: "[&>div]:bg-blue-500" },
                  { label: "Storage Used", value: 90, className: "[&>div]:bg-destructive" },
                ].map(({ label, value, className }) => (
                  <div key={label}>
                    <div className="flex justify-between text-sm mb-1.5">
                      <span className="font-medium">{label}</span>
                      <span className="text-muted-foreground">{value}%</span>
                    </div>
                    {/* Radix injects aria-valuenow={value} automatically */}
                    <Progress value={value} className={className} />
                  </div>
                ))}
              </CardContent>
            </Card>
          </Subsection>
        </section>

        {/* ── NAVIGATION ── */}
        <section className="px-16 py-16 border-b border-border max-w-5xl" id="navigation">
          <SectionLabel>Components</SectionLabel>
          <SectionTitle>Navigation</SectionTitle>
          <SectionDesc>
            shadcn Tabs wraps Radix Tabs — full arrow-key navigation, <code className="bg-muted px-1.5 py-0.5 rounded text-xs font-mono">role="tablist"</code>, and <code className="bg-muted px-1.5 py-0.5 rounded text-xs font-mono">aria-selected</code> out of the box.
          </SectionDesc>

          <Subsection>
            <SubTitle>Top Navigation Bar</SubTitle>
            <div className="rounded-lg border border-border">
              <div className="flex items-center h-14 px-6 bg-card gap-1">
                <span className="text-lg font-extrabold text-primary mr-8">VSee</span>
                {["Dashboard", "Patients", "Schedule", "Messages"].map((item, i) => (
                  <button
                    key={item}
                    className={`px-3 py-1.5 text-sm font-medium rounded-md transition-colors ${
                      i === 0
                        ? "bg-muted text-foreground font-semibold"
                        : "text-muted-foreground hover:text-foreground hover:bg-muted"
                    }`}
                  >
                    {item}
                  </button>
                ))}
                <div className="ml-auto flex items-center gap-2">
                  <Button variant="ghost" size="sm">Help</Button>
                  <Avatar className="h-8 w-8">
                    <AvatarFallback className="text-xs">PN</AvatarFallback>
                  </Avatar>
                </div>
              </div>
            </div>
          </Subsection>

          <Subsection>
            <SubTitle>Tabs (Radix Tabs)</SubTitle>
            <div className="bg-muted rounded-lg p-4 text-xs font-mono text-muted-foreground mb-3">
              {`import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs"`}
            </div>
            {/* TabsList/TabsTrigger from @radix-ui/react-tabs */}
            <Tabs defaultValue="patients">
              <TabsList>
                <TabsTrigger value="patients">Patients</TabsTrigger>
                <TabsTrigger value="visits">All Visits</TabsTrigger>
                <TabsTrigger value="documents">Documents</TabsTrigger>
                <TabsTrigger value="labs">Lab Results</TabsTrigger>
              </TabsList>
              <TabsContent value="patients">
                <Card>
                  <CardContent className="pt-4 text-sm text-muted-foreground">
                    Patients tab content. Arrow keys switch tabs — Radix handles this automatically.
                  </CardContent>
                </Card>
              </TabsContent>
              <TabsContent value="visits"><Card><CardContent className="pt-4 text-sm text-muted-foreground">Visits content</CardContent></Card></TabsContent>
              <TabsContent value="documents"><Card><CardContent className="pt-4 text-sm text-muted-foreground">Documents content</CardContent></Card></TabsContent>
              <TabsContent value="labs"><Card><CardContent className="pt-4 text-sm text-muted-foreground">Lab results content</CardContent></Card></TabsContent>
            </Tabs>
          </Subsection>

          <Subsection>
            <SubTitle>Breadcrumb</SubTitle>
            <Card>
              <CardContent className="pt-4">
                <nav aria-label="Breadcrumb" className="flex items-center gap-2 text-sm">
                  <a href="#" className="text-muted-foreground hover:text-foreground transition-colors">Dashboard</a>
                  <span className="text-border">/</span>
                  <a href="#" className="text-muted-foreground hover:text-foreground transition-colors">Patients</a>
                  <span className="text-border">/</span>
                  <span className="font-medium text-foreground" aria-current="page">Michelle Doe</span>
                </nav>
              </CardContent>
            </Card>
          </Subsection>

          <Subsection>
            <SubTitle>Pagination</SubTitle>
            <Card>
              <CardContent className="pt-4">
                <nav aria-label="Pagination" className="flex items-center gap-1">
                  <Button variant="outline" size="icon" className="h-9 w-9" disabled aria-label="Previous page">
                    <ChevronLeft className="h-4 w-4" />
                  </Button>
                  {[1, 2, 3, 4].map(n => (
                    <Button
                      key={n}
                      variant={n === 1 ? "default" : "outline"}
                      size="icon"
                      className="h-9 w-9"
                      aria-label={`Page ${n}`}
                      aria-current={n === 1 ? "page" : undefined}
                    >
                      {n}
                    </Button>
                  ))}
                  <Button variant="outline" size="icon" className="h-9 w-9" aria-label="Next page">
                    <ChevronRight className="h-4 w-4" />
                  </Button>
                </nav>
              </CardContent>
            </Card>
          </Subsection>
        </section>

        {/* ── DATA DISPLAY ── */}
        <section className="px-16 py-16 border-b border-border max-w-5xl" id="data">
          <SectionLabel>Components</SectionLabel>
          <SectionTitle>Data Display</SectionTitle>
          <SectionDesc>
            shadcn Card (compound component), Table, Avatar. Table has proper <code className="bg-muted px-1.5 py-0.5 rounded text-xs font-mono">scope</code> attributes for Section 508.
          </SectionDesc>

          <Subsection>
            <SubTitle>Patient Card (shadcn Card compound)</SubTitle>
            <div className="bg-muted rounded-lg p-4 text-xs font-mono text-muted-foreground mb-3">
              {`import { Card, CardHeader, CardTitle, CardContent, CardFooter } from "@/components/ui/card"`}
            </div>
            <div className="grid grid-cols-2 gap-4">
              <Card>
                <CardHeader>
                  <div className="flex items-center gap-3 mb-2">
                    {/* Avatar from @radix-ui/react-avatar */}
                    <Avatar className="h-14 w-14">
                      <AvatarFallback className="text-base">MD</AvatarFallback>
                    </Avatar>
                    <div>
                      <CardTitle>Michelle Doe</CardTitle>
                      <CardDescription>Female · 46 years · ID: 10042</CardDescription>
                    </div>
                  </div>
                  <div className="flex gap-2">
                    <Badge variant="success">Active</Badge>
                    <Badge variant="info">Insured</Badge>
                  </div>
                </CardHeader>
                <CardFooter className="gap-2">
                  <Button size="sm">View Chart</Button>
                  <Button variant="outline" size="sm"><MessageSquare className="h-4 w-4" />Message</Button>
                </CardFooter>
              </Card>

              <Card>
                <CardHeader>
                  <div className="flex items-center justify-between">
                    <CardTitle>Upcoming Appointments</CardTitle>
                    <Badge variant="neutral">3</Badge>
                  </div>
                </CardHeader>
                <CardContent className="p-0">
                  {[
                    { name: "Dr. Sarah Chen", date: "Feb 26, 2026 · 10:00 AM", badge: <Badge variant="info">Confirmed</Badge> },
                    { name: "Dr. James Park", date: "Mar 3, 2026 · 2:30 PM", badge: <Badge variant="warning">Pending</Badge> },
                    { name: "Lab Work", date: "Mar 10, 2026 · 8:00 AM", badge: <Badge variant="success">Scheduled</Badge> },
                  ].map(({ name, date, badge }) => (
                    <div key={name} className="flex items-center justify-between px-6 py-3 border-b border-border last:border-0">
                      <div>
                        <div className="text-sm font-semibold">{name}</div>
                        <div className="text-xs text-muted-foreground">{date}</div>
                      </div>
                      {badge}
                    </div>
                  ))}
                </CardContent>
              </Card>
            </div>
          </Subsection>

          <Subsection>
            <SubTitle>Data Table</SubTitle>
            <div className="bg-muted rounded-lg p-4 text-xs font-mono text-muted-foreground mb-3">
              {`import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from "@/components/ui/table"`}
            </div>
            <Card>
              <Table aria-label="Patient list">
                <TableHeader>
                  <TableRow>
                    <TableHead scope="col">Patient</TableHead>
                    <TableHead scope="col">Gender</TableHead>
                    <TableHead scope="col">Age</TableHead>
                    <TableHead scope="col">Last Visit</TableHead>
                    <TableHead scope="col">Status</TableHead>
                    <TableHead scope="col"><span className="sr-only">Actions</span></TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {[
                    { initials: "MD", name: "Michelle Doe", email: "patient@vsee.com", gender: "Female", age: 46, visit: "Feb 20, 2026", badge: <Badge variant="success">Active</Badge> },
                    { initials: "JS", name: "John Smith", email: "john@example.com", gender: "Male", age: 32, visit: "Feb 18, 2026", badge: <Badge variant="warning">Pending</Badge> },
                    { initials: "AW", name: "Alice Wong", email: "alice@example.com", gender: "Female", age: 58, visit: "Jan 15, 2026", badge: <Badge variant="neutral">Inactive</Badge> },
                  ].map(({ initials, name, email, gender, age, visit, badge }) => (
                    <TableRow key={name}>
                      <TableCell>
                        <div className="flex items-center gap-3">
                          <Avatar className="h-8 w-8">
                            <AvatarFallback className="text-xs">{initials}</AvatarFallback>
                          </Avatar>
                          <div>
                            <div className="font-semibold text-sm">{name}</div>
                            <div className="text-xs text-muted-foreground">{email}</div>
                          </div>
                        </div>
                      </TableCell>
                      <TableCell>{gender}</TableCell>
                      <TableCell>{age}</TableCell>
                      <TableCell>{visit}</TableCell>
                      <TableCell>{badge}</TableCell>
                      <TableCell><Button variant="ghost" size="sm">View</Button></TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </Card>
          </Subsection>

          <Subsection>
            <SubTitle>Avatars</SubTitle>
            <Preview>
              {[
                { initials: "A", size: "h-8 w-8 text-xs" },
                { initials: "PN", size: "h-10 w-10 text-sm" },
                { initials: "MD", size: "h-14 w-14 text-base" },
                { initials: "JS", size: "h-20 w-20 text-xl" },
              ].map(({ initials, size }) => (
                <Avatar key={initials} className={size}>
                  <AvatarFallback>{initials}</AvatarFallback>
                </Avatar>
              ))}
            </Preview>
          </Subsection>
        </section>

        {/* ── EMR PATTERNS ── */}
        <section className="px-16 py-16 border-b border-border max-w-5xl" id="emr">
          <SectionLabel>Patterns</SectionLabel>
          <SectionTitle>EMR Patterns</SectionTitle>
          <SectionDesc>Clinical workflow patterns — orders table and vitals card.</SectionDesc>

          <Subsection>
            <SubTitle>Orders Table</SubTitle>
            <Card>
              <CardHeader>
                <div className="flex items-center justify-between">
                  <CardTitle className="flex items-center gap-2">
                    <FlaskConical className="h-4 w-4" /> Lab Orders
                  </CardTitle>
                  <Button size="sm">+ New Order</Button>
                </div>
              </CardHeader>
              <CardContent className="p-0">
                <Table aria-label="Lab orders">
                  <TableHeader>
                    <TableRow>
                      <TableHead scope="col">Order</TableHead>
                      <TableHead scope="col">Type</TableHead>
                      <TableHead scope="col">Ordered By</TableHead>
                      <TableHead scope="col">Date</TableHead>
                      <TableHead scope="col">Status</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {[
                      { order: "CBC with Differential", type: "Lab", by: "Dr. Chen", date: "Feb 25, 2026", status: "ordered" as const },
                      { order: "Lipid Panel", type: "Lab", by: "Dr. Park", date: "Feb 20, 2026", status: "resulted" as const },
                      { order: "Chest X-Ray", type: "Imaging", by: "Dr. Chen", date: "Feb 18, 2026", status: "scheduled" as const },
                      { order: "HbA1c", type: "Lab", by: "Dr. Park", date: "Jan 15, 2026", status: "overdue" as const },
                    ].map(({ order, type, by, date, status }) => (
                      <TableRow key={order}>
                        <TableCell className="font-semibold">{order}</TableCell>
                        <TableCell>{type}</TableCell>
                        <TableCell>{by}</TableCell>
                        <TableCell>{date}</TableCell>
                        <TableCell><StatusBadge variant={status}>{status.charAt(0).toUpperCase() + status.slice(1)}</StatusBadge></TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              </CardContent>
            </Card>
          </Subsection>

          <Subsection>
            <SubTitle>Vitals Card</SubTitle>
            <Card className="max-w-md">
              <CardHeader>
                <div className="flex items-center justify-between">
                  <CardTitle>Latest Vitals</CardTitle>
                  <span className="text-sm text-muted-foreground">Feb 26, 2026</span>
                </div>
              </CardHeader>
              <CardContent>
                <div className="grid grid-cols-3 gap-4" aria-label="Patient vitals">
                  {[
                    { value: "120/80", label: "Blood Pressure", color: "text-primary" },
                    { value: "72", label: "Heart Rate", color: "text-foreground" },
                    { value: "98.6°", label: "Temperature", color: "text-foreground" },
                    { value: "98%", label: "SpO2", color: "text-green-600" },
                    { value: "16", label: "Resp Rate", color: "text-foreground" },
                    { value: "28.5", label: "BMI", color: "text-amber-600" },
                  ].map(({ value, label, color }) => (
                    <div key={label} className="text-center">
                      <div className={`text-2xl font-bold ${color}`}>{value}</div>
                      <div className="text-xs text-muted-foreground font-medium mt-0.5">{label}</div>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>
          </Subsection>
        </section>

        {/* ── THEMING ── */}
        <section className="px-16 py-16 border-b border-border max-w-5xl" id="theming">
          <SectionLabel>Patterns</SectionLabel>
          <SectionTitle>White-Label Theming</SectionTitle>
          <SectionDesc>
            shadcn's oklch variables make white-labeling trivial. Override <code className="bg-muted px-1.5 py-0.5 rounded text-xs font-mono">--primary</code> and <code className="bg-muted px-1.5 py-0.5 rounded text-xs font-mono">--ring</code> per tenant. Only 4–5 variables need to change.
          </SectionDesc>

          <div className="grid grid-cols-3 gap-4 mb-6">
            {[
              { name: "VSee Default", color: "#0D875C", btnBg: "bg-[#0D875C]", btnText: "text-white", outlineColor: "border-[#0D875C] text-[#0D875C]" },
              { name: "Blue Variant", color: "#2563EB", btnBg: "bg-[#2563EB]", btnText: "text-white", outlineColor: "border-[#2563EB] text-[#2563EB]" },
              { name: "Purple Variant", color: "#7C3AED", btnBg: "bg-[#7C3AED]", btnText: "text-white", outlineColor: "border-[#7C3AED] text-[#7C3AED]" },
            ].map(({ name, color, btnBg, btnText, outlineColor }) => (
              <Card key={name}>
                <CardHeader className="pb-3">
                  <div className="flex items-center gap-2">
                    <div className="w-3 h-3 rounded-full" style={{ background: color }} />
                    <CardTitle className="text-sm">{name}</CardTitle>
                  </div>
                </CardHeader>
                <CardContent className="flex gap-2">
                  <button className={`px-4 py-2 rounded-md text-sm font-medium ${btnBg} ${btnText}`}>Default</button>
                  <button className={`px-4 py-2 rounded-md text-sm font-medium border bg-background ${outlineColor}`}>Outline</button>
                </CardContent>
              </Card>
            ))}
          </div>

          <Card>
            <CardContent className="pt-6">
              <pre className="bg-gray-950 text-gray-200 rounded-lg p-5 text-xs font-mono leading-relaxed overflow-x-auto">
{`/* index.css — override for a blue-health tenant */
/* Only 4 variables change — everything else inherits */

[data-theme="blue-health"] {
  --primary:            221 83% 53%;   /* #2563EB */
  --primary-foreground: 0 0% 100%;
  --accent:             221 83% 95%;
  --accent-foreground:  221 83% 35%;
  --ring:               221 83% 53%;
}`}
              </pre>
            </CardContent>
          </Card>
        </section>

        {/* ── TOKENS ── */}
        <section className="px-16 py-16 border-b border-border max-w-5xl" id="tokens">
          <SectionLabel>Engineering</SectionLabel>
          <SectionTitle>Design Tokens</SectionTitle>
          <SectionDesc>
            The complete <code className="bg-muted px-1.5 py-0.5 rounded text-xs font-mono">:root</code> block from <code className="bg-muted px-1.5 py-0.5 rounded text-xs font-mono">src/index.css</code>. Copy into any shadcn project.
          </SectionDesc>

          <Card>
            <CardContent className="pt-6">
              <pre className="bg-gray-950 text-gray-200 rounded-lg p-5 text-xs font-mono leading-relaxed overflow-x-auto">
{`/* VSee Clinic × shadcn/ui Tokens — v4.0  */
/* src/index.css                           */

@import "tailwindcss";

@theme inline {
  --color-background:          var(--background);
  --color-foreground:          var(--foreground);
  --color-primary:             var(--primary);
  --color-primary-foreground:  var(--primary-foreground);
  --color-secondary:           var(--secondary);
  --color-muted:               var(--muted);
  --color-muted-foreground:    var(--muted-foreground);
  --color-accent:              var(--accent);
  --color-accent-foreground:   var(--accent-foreground);
  --color-destructive:         var(--destructive);
  --color-border:              var(--border);
  --color-input:               var(--input);
  --color-ring:                var(--ring);
  --radius-lg:                 var(--radius);
}

:root {
  /* VSee Green #0D875C */
  --primary:             oklch(0.52 0.14 162);
  --primary-foreground:  oklch(1 0 0);

  --background:          oklch(1 0 0);
  --foreground:          oklch(0.16 0.02 265);
  --card:                oklch(1 0 0);
  --muted:               oklch(0.96 0.005 265);
  --muted-foreground:    oklch(0.52 0.01 265);
  --accent:              oklch(0.95 0.04 162);
  --accent-foreground:   oklch(0.35 0.1 162);
  --destructive:         oklch(0.64 0.2 25);
  --border:              oklch(0.92 0.005 265);
  --input:               oklch(0.92 0.005 265);
  --ring:                oklch(0.52 0.14 162);
  --radius:              0.5rem;
}`}
              </pre>
            </CardContent>
          </Card>

          <div className="mt-6">
            <SubTitle>Install Commands</SubTitle>
            <Card>
              <CardContent className="pt-6">
                <pre className="bg-gray-950 text-gray-200 rounded-lg p-5 text-xs font-mono leading-relaxed overflow-x-auto">
{`# 1. Install all dependencies
npm install

# 2. Start dev server
npm run dev

# 3. Add more shadcn components as needed
npx shadcn@latest add dialog
npx shadcn@latest add select
npx shadcn@latest add tooltip
npx shadcn@latest add radio-group
npx shadcn@latest add date-picker`}
                </pre>
              </CardContent>
            </Card>
          </div>
        </section>

        {/* FOOTER */}
        <footer className="text-center py-16 text-muted-foreground border-t border-border">
          <div className="text-xl font-extrabold text-primary mb-2">VSee</div>
          <div className="text-sm">Design System v4 · shadcn/ui Edition · March 2026</div>
          <div className="text-xs mt-2">Inter · 4px grid · WCAG AA · Section 508 · White-label ready</div>
          <div className="flex items-center justify-center gap-2 mt-4">
            <Badge variant="outline">shadcn/ui</Badge>
            <Badge variant="outline">Radix UI</Badge>
            <Badge variant="outline">Tailwind v4</Badge>
            <Badge variant="outline">lucide-react</Badge>
          </div>
        </footer>

      </div>
    </div>
  )
}
